### ISSUE TITLE
代码好像运行不了=^=

### ISSUE THREAD

**Issue by zhangknife** [ClausewitzCPU0/SC2AI#1]
正常运行会有报错，把报错的语句改掉后会找不到地图 提示E:\ProgramData\Anaconda3\envs\python36\python.exe E:/ProgramData/SC2AI-master/ch1.0_Collecting_Minerals.py
INFO:sc2.protocol:Client status changed to Status.launched (was None)
INFO:sc2.sc2process:kill_switch: Process cleanup
INFO:sc2.sc2process:Cleaning up...
INFO:sc2.sc2process:Cleanup complete
Traceback (most recent call last):
  File "E:/ProgramData/SC2AI-master/ch1.0_Collecting_Minerals.py", line 33, in <module>
    main()
  File "E:/ProgramData/SC2AI-master/ch1.0_Collecting_Minerals.py", line 29, in main
    Computer(Race.Protoss, Difficulty.Easy)], realtime=True)
  File "E:\ProgramData\Anaconda3\envs\python36\lib\site-packages\sc2\main.py", line 326, in run_game
    _host_game(map_settings, players, **kwargs)
  File "E:\ProgramData\Anaconda3\envs\python36\lib\asyncio\base_events.py", line 473, in run_until_complete
    return future.result()
  File "E:\ProgramData\Anaconda3\envs\python36\lib\site-packages\sc2\main.py", line 250, in _host_game
    client = await _setup_host_game(server, map_settings, players, realtime, random_seed)
  File "E:\ProgramData\Anaconda3\envs\python36\lib\site-packages\sc2\main.py", line 230, in _setup_host_game
    r = await server.create_game(map_settings, players, realtime, random_seed)
  File "E:\ProgramData\Anaconda3\envs\python36\lib\site-packages\sc2\controller.py", line 21, in create_game
    req = sc_pb.RequestCreateGame(local_map=sc_pb.LocalMap(map_path=str(game_map.relative_path)), realtime=realtime)
AttributeError: 'NoneType' object has no attribute 'relative_path'
求指点

**Comment by CaptainJi** [comment]
你下载的地图对吗

**Comment by QingyvHan** [comment]
> 
> 
> 正常运行会有报错，把报错的语句改掉后会找不到地图 提示E:\ProgramData\Anaconda3\envs\python36\python.exe E:/ProgramData/SC2AI-master/ch1.0_Collecting_Minerals.py
> INFO:sc2.protocol:Client status changed to Status.launched (was None)
> INFO:sc2.sc2process:kill_switch: Process cleanup
> INFO:sc2.sc2process:Cleaning up...
> INFO:sc2.sc2process:Cleanup complete
> Traceback (most recent call last):
> File "E:/ProgramData/SC2AI-master/ch1.0_Collecting_Minerals.py", line 33, in
> main()
> File "E:/ProgramData/SC2AI-master/ch1.0_Collecting_Minerals.py", line 29, in main
> Computer(Race.Protoss, Difficulty.Easy)], realtime=True)
> File "E:\ProgramData\Anaconda3\envs\python36\lib\site-packages\sc2\main.py", line 326, in run_game
> _host_game(map_settings, players, **kwargs)
> File "E:\ProgramData\Anaconda3\envs\python36\lib\asyncio\base_events.py", line 473, in run_until_complete
> return future.result()
> File "E:\ProgramData\Anaconda3\envs\python36\lib\site-packages\sc2\main.py", line 250, in _host_game
> client = await _setup_host_game(server, map_settings, players, realtime, random_seed)
> File "E:\ProgramData\Anaconda3\envs\python36\lib\site-packages\sc2\main.py", line 230, in _setup_host_game
> r = await server.create_game(map_settings, players, realtime, random_seed)
> File "E:\ProgramData\Anaconda3\envs\python36\lib\site-packages\sc2\controller.py", line 21, in create_game
> req = sc_pb.RequestCreateGame(local_map=sc_pb.LocalMap(map_path=str(game_map.relative_path)), realtime=realtime)
> AttributeError: 'NoneType' object has no attribute 'relative_path'
> 求指点

随便改个地图就可以跑
